<?php namespace App\Models;

/**
 * Eloquent class to describe the tblfiles table
 *
 * automatically generated by ModelGenerator.php
 */
class Tblfiles extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'tblfiles';

    protected $fillable = array('file','file_type');


}
